### GET POSTS
GET http://localhost:3001/api/post
### GET SINGLE POST
GET http://localhost:3001/api/post/65c78e2a7bd3e521cf94f9cd
### CREATE A POST
POST http://localhost:3001/api/post
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.NjVjNzhjYTVmMTRkODQ5MzhkOGU4OGQz.McvdOcMCZPC1xWNmGwHvrWWycdD1tjGCKUb1jIEOw84


{
  "description": "test2 description.",
  "price": 699,
  "category": "test2 category",
  "title": "test2 title"
}

### UPDATE A POST
PATCH http://localhost:3001/api/post/65c7436099b1d6edec8e8951
content-type: application/json

{
    "title":"a",
    "public": true
}


### DELETE POST
DELETE http://localhost:3001/api/post/65c763ce6958bf47fab98b39
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.NjVjNzhjYTVmMTRkODQ5MzhkOGU4OGQz.McvdOcMCZPC1xWNmGwHvrWWycdD1tjGCKUb1jIEOw84

