### SIGN IN USER
POST http://localhost:3001/api/auth/sign-in
content-type: application/json

{
    "email": "ajmir@gmail.com",
    "password": "123"
}
### SIGN UP USER
POST http://localhost:3001/api/auth/sign-up
content-type: application/json


{
    "email": "ram@gmail.com",
    "password": "123"
}
### GET AUTH USER
GET http://localhost:3001/api/auth
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.NjVjNzhjYTVmMTRkODQ5MzhkOGU4OGQz.McvdOcMCZPC1xWNmGwHvrWWycdD1tjGCKUb1jIEOw84